/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as MediaCenterRouteImport } from './routes/media-center'
import { Route as LandShareRouteImport } from './routes/land-share'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as EmiCalculatorRouteImport } from './routes/emi-calculator'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as BrochureRouteImport } from './routes/brochure'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BookVisitRouteImport } from './routes/book-visit'
import { Route as BookApartmentRouteImport } from './routes/book-apartment'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsOngoingRouteImport } from './routes/projects.ongoing'
import { Route as ProjectsCompletedRouteImport } from './routes/projects.completed'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardFavoritesRouteImport } from './routes/_authenticated/dashboard.favorites'
import { Route as AuthenticatedDashboardEmiPlannerRouteImport } from './routes/_authenticated/dashboard.emi-planner'
import { Route as AuthenticatedDashboardDocumentsRouteImport } from './routes/_authenticated/dashboard.documents'
import { Route as AuthenticatedDashboardCompareRouteImport } from './routes/_authenticated/dashboard.compare'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard.bookings'
import { Route as AuthenticatedDashboardAlertsRouteImport } from './routes/_authenticated/dashboard.alerts'
import { Route as AdminAdminVideosRouteImport } from './routes/_admin/admin.videos'
import { Route as AdminAdminTeamRouteImport } from './routes/_admin/admin.team'
import { Route as AdminAdminSiteVisitsRouteImport } from './routes/_admin/admin.site-visits'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminSeoRouteImport } from './routes/_admin/admin.seo'
import { Route as AdminAdminRolesRouteImport } from './routes/_admin/admin.roles'
import { Route as AdminAdminReviewsRouteImport } from './routes/_admin/admin.reviews'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin.reports'
import { Route as AdminAdminProjectsRouteImport } from './routes/_admin/admin.projects'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin/admin.payments'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin/admin.notifications'
import { Route as AdminAdminNewsletterRouteImport } from './routes/_admin/admin.newsletter'
import { Route as AdminAdminMessagesRouteImport } from './routes/_admin/admin.messages'
import { Route as AdminAdminMediaRouteImport } from './routes/_admin/admin.media'
import { Route as AdminAdminMarketingRouteImport } from './routes/_admin/admin.marketing'
import { Route as AdminAdminLeadsRouteImport } from './routes/_admin/admin.leads'
import { Route as AdminAdminInventoryRouteImport } from './routes/_admin/admin.inventory'
import { Route as AdminAdminGalleryRouteImport } from './routes/_admin/admin.gallery'
import { Route as AdminAdminCustomersRouteImport } from './routes/_admin/admin.customers'
import { Route as AdminAdminCareersRouteImport } from './routes/_admin/admin.careers'
import { Route as AdminAdminCalendarRouteImport } from './routes/_admin/admin.calendar'
import { Route as AdminAdminBranchesRouteImport } from './routes/_admin/admin.branches'
import { Route as AdminAdminBookingsRouteImport } from './routes/_admin/admin.bookings'
import { Route as AdminAdminBlogRouteImport } from './routes/_admin/admin.blog'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin/admin.audit'
import { Route as AdminAdminApartmentsRouteImport } from './routes/_admin/admin.apartments'
import { Route as AdminAdminAnnouncementsRouteImport } from './routes/_admin/admin.announcements'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin.analytics'
import { Route as ProjectsSlugFlatsFlatRouteImport } from './routes/projects.$slug.flats.$flat'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCenterRoute = MediaCenterRouteImport.update({
  id: '/media-center',
  path: '/media-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LandShareRoute = LandShareRouteImport.update({
  id: '/land-share',
  path: '/land-share',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiCalculatorRoute = EmiCalculatorRouteImport.update({
  id: '/emi-calculator',
  path: '/emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BrochureRoute = BrochureRouteImport.update({
  id: '/brochure',
  path: '/brochure',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVisitRoute = BookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const BookApartmentRoute = BookApartmentRouteImport.update({
  id: '/book-apartment',
  path: '/book-apartment',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsOngoingRoute = ProjectsOngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCompletedRoute = ProjectsCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFavoritesRoute =
  AuthenticatedDashboardFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEmiPlannerRoute =
  AuthenticatedDashboardEmiPlannerRouteImport.update({
    id: '/emi-planner',
    path: '/emi-planner',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumentsRoute =
  AuthenticatedDashboardDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCompareRoute =
  AuthenticatedDashboardCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAlertsRoute =
  AuthenticatedDashboardAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminVideosRoute = AdminAdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTeamRoute = AdminAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSiteVisitsRoute = AdminAdminSiteVisitsRouteImport.update({
  id: '/site-visits',
  path: '/site-visits',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSeoRoute = AdminAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRolesRoute = AdminAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReviewsRoute = AdminAdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProjectsRoute = AdminAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminNewsletterRoute = AdminAdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMediaRoute = AdminAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMarketingRoute = AdminAdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLeadsRoute = AdminAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminInventoryRoute = AdminAdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminGalleryRoute = AdminAdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCustomersRoute = AdminAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCareersRoute = AdminAdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCalendarRoute = AdminAdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBranchesRoute = AdminAdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBookingsRoute = AdminAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBlogRoute = AdminAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminApartmentsRoute = AdminAdminApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAnnouncementsRoute = AdminAdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ProjectsSlugFlatsFlatRoute = ProjectsSlugFlatsFlatRouteImport.update({
  id: '/flats/$flat',
  path: '/flats/$flat',
  getParentRoute: () => ProjectsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/agreement': typeof AgreementRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book-apartment': typeof BookApartmentRoute
  '/book-visit': typeof BookVisitRoute
  '/booking': typeof BookingRoute
  '/brochure': typeof BrochureRoute
  '/callback': typeof CallbackRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/estimator': typeof EstimatorRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/land-share': typeof LandShareRoute
  '/media-center': typeof MediaCenterRoute
  '/my-bookings': typeof MyBookingsRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recommend': typeof RecommendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/translate': typeof ApiTranslateRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/announcements': typeof AdminAdminAnnouncementsRoute
  '/admin/apartments': typeof AdminAdminApartmentsRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/blog': typeof AdminAdminBlogRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/branches': typeof AdminAdminBranchesRoute
  '/admin/calendar': typeof AdminAdminCalendarRoute
  '/admin/careers': typeof AdminAdminCareersRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/gallery': typeof AdminAdminGalleryRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/leads': typeof AdminAdminLeadsRoute
  '/admin/marketing': typeof AdminAdminMarketingRoute
  '/admin/media': typeof AdminAdminMediaRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/newsletter': typeof AdminAdminNewsletterRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/seo': typeof AdminAdminSeoRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/site-visits': typeof AdminAdminSiteVisitsRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/admin/videos': typeof AdminAdminVideosRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/compare': typeof AuthenticatedDashboardCompareRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/emi-planner': typeof AuthenticatedDashboardEmiPlannerRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/projects/$slug/flats/$flat': typeof ProjectsSlugFlatsFlatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/agreement': typeof AgreementRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book-apartment': typeof BookApartmentRoute
  '/book-visit': typeof BookVisitRoute
  '/booking': typeof BookingRoute
  '/brochure': typeof BrochureRoute
  '/callback': typeof CallbackRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/estimator': typeof EstimatorRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/land-share': typeof LandShareRoute
  '/media-center': typeof MediaCenterRoute
  '/my-bookings': typeof MyBookingsRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/recommend': typeof RecommendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/translate': typeof ApiTranslateRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/announcements': typeof AdminAdminAnnouncementsRoute
  '/admin/apartments': typeof AdminAdminApartmentsRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/blog': typeof AdminAdminBlogRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/branches': typeof AdminAdminBranchesRoute
  '/admin/calendar': typeof AdminAdminCalendarRoute
  '/admin/careers': typeof AdminAdminCareersRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/gallery': typeof AdminAdminGalleryRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/leads': typeof AdminAdminLeadsRoute
  '/admin/marketing': typeof AdminAdminMarketingRoute
  '/admin/media': typeof AdminAdminMediaRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/newsletter': typeof AdminAdminNewsletterRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/projects': typeof AdminAdminProjectsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/seo': typeof AdminAdminSeoRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/site-visits': typeof AdminAdminSiteVisitsRoute
  '/admin/team': typeof AdminAdminTeamRoute
  '/admin/videos': typeof AdminAdminVideosRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/compare': typeof AuthenticatedDashboardCompareRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/emi-planner': typeof AuthenticatedDashboardEmiPlannerRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/projects/$slug/flats/$flat': typeof ProjectsSlugFlatsFlatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/agreement': typeof AgreementRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book-apartment': typeof BookApartmentRoute
  '/book-visit': typeof BookVisitRoute
  '/booking': typeof BookingRoute
  '/brochure': typeof BrochureRoute
  '/callback': typeof CallbackRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/emi-calculator': typeof EmiCalculatorRoute
  '/estimator': typeof EstimatorRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journey': typeof JourneyRoute
  '/land-share': typeof LandShareRoute
  '/media-center': typeof MediaCenterRoute
  '/my-bookings': typeof MyBookingsRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recommend': typeof RecommendRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/videos': typeof VideosRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/translate': typeof ApiTranslateRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/announcements': typeof AdminAdminAnnouncementsRoute
  '/_admin/admin/apartments': typeof AdminAdminApartmentsRoute
  '/_admin/admin/audit': typeof AdminAdminAuditRoute
  '/_admin/admin/blog': typeof AdminAdminBlogRoute
  '/_admin/admin/bookings': typeof AdminAdminBookingsRoute
  '/_admin/admin/branches': typeof AdminAdminBranchesRoute
  '/_admin/admin/calendar': typeof AdminAdminCalendarRoute
  '/_admin/admin/careers': typeof AdminAdminCareersRoute
  '/_admin/admin/customers': typeof AdminAdminCustomersRoute
  '/_admin/admin/gallery': typeof AdminAdminGalleryRoute
  '/_admin/admin/inventory': typeof AdminAdminInventoryRoute
  '/_admin/admin/leads': typeof AdminAdminLeadsRoute
  '/_admin/admin/marketing': typeof AdminAdminMarketingRoute
  '/_admin/admin/media': typeof AdminAdminMediaRoute
  '/_admin/admin/messages': typeof AdminAdminMessagesRoute
  '/_admin/admin/newsletter': typeof AdminAdminNewsletterRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/projects': typeof AdminAdminProjectsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/reviews': typeof AdminAdminReviewsRoute
  '/_admin/admin/roles': typeof AdminAdminRolesRoute
  '/_admin/admin/seo': typeof AdminAdminSeoRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/site-visits': typeof AdminAdminSiteVisitsRoute
  '/_admin/admin/team': typeof AdminAdminTeamRoute
  '/_admin/admin/videos': typeof AdminAdminVideosRoute
  '/_authenticated/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/compare': typeof AuthenticatedDashboardCompareRoute
  '/_authenticated/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/_authenticated/dashboard/emi-planner': typeof AuthenticatedDashboardEmiPlannerRoute
  '/_authenticated/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/projects/$slug/flats/$flat': typeof ProjectsSlugFlatsFlatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/agreement'
    | '/apartments'
    | '/auth'
    | '/blog'
    | '/book-apartment'
    | '/book-visit'
    | '/booking'
    | '/brochure'
    | '/callback'
    | '/careers'
    | '/contact'
    | '/downloads'
    | '/emi-calculator'
    | '/estimator'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/land-share'
    | '/media-center'
    | '/my-bookings'
    | '/payment'
    | '/privacy'
    | '/projects'
    | '/recommend'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/videos'
    | '/admin'
    | '/dashboard'
    | '/api/translate'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/projects/'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/apartments'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/calendar'
    | '/admin/careers'
    | '/admin/customers'
    | '/admin/gallery'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/site-visits'
    | '/admin/team'
    | '/admin/videos'
    | '/dashboard/alerts'
    | '/dashboard/bookings'
    | '/dashboard/compare'
    | '/dashboard/documents'
    | '/dashboard/emi-planner'
    | '/dashboard/favorites'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/projects/$slug/flats/$flat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/agreement'
    | '/apartments'
    | '/auth'
    | '/blog'
    | '/book-apartment'
    | '/book-visit'
    | '/booking'
    | '/brochure'
    | '/callback'
    | '/careers'
    | '/contact'
    | '/downloads'
    | '/emi-calculator'
    | '/estimator'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/land-share'
    | '/media-center'
    | '/my-bookings'
    | '/payment'
    | '/privacy'
    | '/recommend'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/videos'
    | '/admin'
    | '/dashboard'
    | '/api/translate'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/projects'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/apartments'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/calendar'
    | '/admin/careers'
    | '/admin/customers'
    | '/admin/gallery'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/site-visits'
    | '/admin/team'
    | '/admin/videos'
    | '/dashboard/alerts'
    | '/dashboard/bookings'
    | '/dashboard/compare'
    | '/dashboard/documents'
    | '/dashboard/emi-planner'
    | '/dashboard/favorites'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/projects/$slug/flats/$flat'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/about'
    | '/achievements'
    | '/agreement'
    | '/apartments'
    | '/auth'
    | '/blog'
    | '/book-apartment'
    | '/book-visit'
    | '/booking'
    | '/brochure'
    | '/callback'
    | '/careers'
    | '/contact'
    | '/downloads'
    | '/emi-calculator'
    | '/estimator'
    | '/faq'
    | '/gallery'
    | '/journey'
    | '/land-share'
    | '/media-center'
    | '/my-bookings'
    | '/payment'
    | '/privacy'
    | '/projects'
    | '/recommend'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/videos'
    | '/_admin/admin'
    | '/_authenticated/dashboard'
    | '/api/translate'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/projects/'
    | '/_admin/admin/analytics'
    | '/_admin/admin/announcements'
    | '/_admin/admin/apartments'
    | '/_admin/admin/audit'
    | '/_admin/admin/blog'
    | '/_admin/admin/bookings'
    | '/_admin/admin/branches'
    | '/_admin/admin/calendar'
    | '/_admin/admin/careers'
    | '/_admin/admin/customers'
    | '/_admin/admin/gallery'
    | '/_admin/admin/inventory'
    | '/_admin/admin/leads'
    | '/_admin/admin/marketing'
    | '/_admin/admin/media'
    | '/_admin/admin/messages'
    | '/_admin/admin/newsletter'
    | '/_admin/admin/notifications'
    | '/_admin/admin/payments'
    | '/_admin/admin/projects'
    | '/_admin/admin/reports'
    | '/_admin/admin/reviews'
    | '/_admin/admin/roles'
    | '/_admin/admin/seo'
    | '/_admin/admin/settings'
    | '/_admin/admin/site-visits'
    | '/_admin/admin/team'
    | '/_admin/admin/videos'
    | '/_authenticated/dashboard/alerts'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/compare'
    | '/_authenticated/dashboard/documents'
    | '/_authenticated/dashboard/emi-planner'
    | '/_authenticated/dashboard/favorites'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/profile'
    | '/projects/$slug/flats/$flat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AgreementRoute: typeof AgreementRoute
  ApartmentsRoute: typeof ApartmentsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  BookApartmentRoute: typeof BookApartmentRoute
  BookVisitRoute: typeof BookVisitRoute
  BookingRoute: typeof BookingRoute
  BrochureRoute: typeof BrochureRoute
  CallbackRoute: typeof CallbackRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  EmiCalculatorRoute: typeof EmiCalculatorRoute
  EstimatorRoute: typeof EstimatorRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  JourneyRoute: typeof JourneyRoute
  LandShareRoute: typeof LandShareRoute
  MediaCenterRoute: typeof MediaCenterRoute
  MyBookingsRoute: typeof MyBookingsRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RecommendRoute: typeof RecommendRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  VideosRoute: typeof VideosRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-center': {
      id: '/media-center'
      path: '/media-center'
      fullPath: '/media-center'
      preLoaderRoute: typeof MediaCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land-share': {
      id: '/land-share'
      path: '/land-share'
      fullPath: '/land-share'
      preLoaderRoute: typeof LandShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi-calculator': {
      id: '/emi-calculator'
      path: '/emi-calculator'
      fullPath: '/emi-calculator'
      preLoaderRoute: typeof EmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brochure': {
      id: '/brochure'
      path: '/brochure'
      fullPath: '/brochure'
      preLoaderRoute: typeof BrochureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-visit': {
      id: '/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof BookVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-apartment': {
      id: '/book-apartment'
      path: '/book-apartment'
      fullPath: '/book-apartment'
      preLoaderRoute: typeof BookApartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/ongoing': {
      id: '/projects/ongoing'
      path: '/ongoing'
      fullPath: '/projects/ongoing'
      preLoaderRoute: typeof ProjectsOngoingRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/completed': {
      id: '/projects/completed'
      path: '/completed'
      fullPath: '/projects/completed'
      preLoaderRoute: typeof ProjectsCompletedRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/favorites': {
      id: '/_authenticated/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof AuthenticatedDashboardFavoritesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/emi-planner': {
      id: '/_authenticated/dashboard/emi-planner'
      path: '/emi-planner'
      fullPath: '/dashboard/emi-planner'
      preLoaderRoute: typeof AuthenticatedDashboardEmiPlannerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documents': {
      id: '/_authenticated/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/compare': {
      id: '/_authenticated/dashboard/compare'
      path: '/compare'
      fullPath: '/dashboard/compare'
      preLoaderRoute: typeof AuthenticatedDashboardCompareRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/alerts': {
      id: '/_authenticated/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof AuthenticatedDashboardAlertsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/videos': {
      id: '/_admin/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminAdminVideosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/team': {
      id: '/_admin/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAdminTeamRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/site-visits': {
      id: '/_admin/admin/site-visits'
      path: '/site-visits'
      fullPath: '/admin/site-visits'
      preLoaderRoute: typeof AdminAdminSiteVisitsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/seo': {
      id: '/_admin/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminAdminSeoRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/roles': {
      id: '/_admin/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminAdminRolesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/reviews': {
      id: '/_admin/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAdminReviewsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/projects': {
      id: '/_admin/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminAdminProjectsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/newsletter': {
      id: '/_admin/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminAdminNewsletterRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/messages': {
      id: '/_admin/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/media': {
      id: '/_admin/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAdminMediaRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/marketing': {
      id: '/_admin/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminAdminMarketingRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/leads': {
      id: '/_admin/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminAdminLeadsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/inventory': {
      id: '/_admin/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminAdminInventoryRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/gallery': {
      id: '/_admin/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminAdminGalleryRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/customers': {
      id: '/_admin/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAdminCustomersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/careers': {
      id: '/_admin/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminAdminCareersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/calendar': {
      id: '/_admin/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminAdminCalendarRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/branches': {
      id: '/_admin/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminAdminBranchesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/bookings': {
      id: '/_admin/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminAdminBookingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/blog': {
      id: '/_admin/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminAdminBlogRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/audit': {
      id: '/_admin/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/apartments': {
      id: '/_admin/admin/apartments'
      path: '/apartments'
      fullPath: '/admin/apartments'
      preLoaderRoute: typeof AdminAdminApartmentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/announcements': {
      id: '/_admin/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAdminAnnouncementsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/projects/$slug/flats/$flat': {
      id: '/projects/$slug/flats/$flat'
      path: '/flats/$flat'
      fullPath: '/projects/$slug/flats/$flat'
      preLoaderRoute: typeof ProjectsSlugFlatsFlatRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminAnnouncementsRoute: typeof AdminAdminAnnouncementsRoute
  AdminAdminApartmentsRoute: typeof AdminAdminApartmentsRoute
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminBlogRoute: typeof AdminAdminBlogRoute
  AdminAdminBookingsRoute: typeof AdminAdminBookingsRoute
  AdminAdminBranchesRoute: typeof AdminAdminBranchesRoute
  AdminAdminCalendarRoute: typeof AdminAdminCalendarRoute
  AdminAdminCareersRoute: typeof AdminAdminCareersRoute
  AdminAdminCustomersRoute: typeof AdminAdminCustomersRoute
  AdminAdminGalleryRoute: typeof AdminAdminGalleryRoute
  AdminAdminInventoryRoute: typeof AdminAdminInventoryRoute
  AdminAdminLeadsRoute: typeof AdminAdminLeadsRoute
  AdminAdminMarketingRoute: typeof AdminAdminMarketingRoute
  AdminAdminMediaRoute: typeof AdminAdminMediaRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminNewsletterRoute: typeof AdminAdminNewsletterRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminProjectsRoute: typeof AdminAdminProjectsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminReviewsRoute: typeof AdminAdminReviewsRoute
  AdminAdminRolesRoute: typeof AdminAdminRolesRoute
  AdminAdminSeoRoute: typeof AdminAdminSeoRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSiteVisitsRoute: typeof AdminAdminSiteVisitsRoute
  AdminAdminTeamRoute: typeof AdminAdminTeamRoute
  AdminAdminVideosRoute: typeof AdminAdminVideosRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminAnnouncementsRoute: AdminAdminAnnouncementsRoute,
  AdminAdminApartmentsRoute: AdminAdminApartmentsRoute,
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminBlogRoute: AdminAdminBlogRoute,
  AdminAdminBookingsRoute: AdminAdminBookingsRoute,
  AdminAdminBranchesRoute: AdminAdminBranchesRoute,
  AdminAdminCalendarRoute: AdminAdminCalendarRoute,
  AdminAdminCareersRoute: AdminAdminCareersRoute,
  AdminAdminCustomersRoute: AdminAdminCustomersRoute,
  AdminAdminGalleryRoute: AdminAdminGalleryRoute,
  AdminAdminInventoryRoute: AdminAdminInventoryRoute,
  AdminAdminLeadsRoute: AdminAdminLeadsRoute,
  AdminAdminMarketingRoute: AdminAdminMarketingRoute,
  AdminAdminMediaRoute: AdminAdminMediaRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminNewsletterRoute: AdminAdminNewsletterRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminProjectsRoute: AdminAdminProjectsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminReviewsRoute: AdminAdminReviewsRoute,
  AdminAdminRolesRoute: AdminAdminRolesRoute,
  AdminAdminSeoRoute: AdminAdminSeoRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSiteVisitsRoute: AdminAdminSiteVisitsRoute,
  AdminAdminTeamRoute: AdminAdminTeamRoute,
  AdminAdminVideosRoute: AdminAdminVideosRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAlertsRoute: typeof AuthenticatedDashboardAlertsRoute
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardCompareRoute: typeof AuthenticatedDashboardCompareRoute
  AuthenticatedDashboardDocumentsRoute: typeof AuthenticatedDashboardDocumentsRoute
  AuthenticatedDashboardEmiPlannerRoute: typeof AuthenticatedDashboardEmiPlannerRoute
  AuthenticatedDashboardFavoritesRoute: typeof AuthenticatedDashboardFavoritesRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAlertsRoute: AuthenticatedDashboardAlertsRoute,
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardCompareRoute: AuthenticatedDashboardCompareRoute,
    AuthenticatedDashboardDocumentsRoute: AuthenticatedDashboardDocumentsRoute,
    AuthenticatedDashboardEmiPlannerRoute:
      AuthenticatedDashboardEmiPlannerRoute,
    AuthenticatedDashboardFavoritesRoute: AuthenticatedDashboardFavoritesRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProjectsSlugRouteChildren {
  ProjectsSlugFlatsFlatRoute: typeof ProjectsSlugFlatsFlatRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugFlatsFlatRoute: ProjectsSlugFlatsFlatRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
  ProjectsCompletedRoute: typeof ProjectsCompletedRoute
  ProjectsOngoingRoute: typeof ProjectsOngoingRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
  ProjectsCompletedRoute: ProjectsCompletedRoute,
  ProjectsOngoingRoute: ProjectsOngoingRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AgreementRoute: AgreementRoute,
  ApartmentsRoute: ApartmentsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  BookApartmentRoute: BookApartmentRoute,
  BookVisitRoute: BookVisitRoute,
  BookingRoute: BookingRoute,
  BrochureRoute: BrochureRoute,
  CallbackRoute: CallbackRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  EmiCalculatorRoute: EmiCalculatorRoute,
  EstimatorRoute: EstimatorRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  JourneyRoute: JourneyRoute,
  LandShareRoute: LandShareRoute,
  MediaCenterRoute: MediaCenterRoute,
  MyBookingsRoute: MyBookingsRoute,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RecommendRoute: RecommendRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  VideosRoute: VideosRoute,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
